import Database from 'better-sqlite3'
import { v4 as uuid } from 'uuid'
import type { LoreEntry, LoreCategory, ContextLayer } from '@novelforge/shared'

export function createLoreEntry(db: Database.Database, data: Omit<LoreEntry, 'id' | 'updatedAt'>): LoreEntry {
  const id = uuid()
  db.prepare(`
    INSERT INTO lore_entries (id, project_id, category, key, title, content, auto_generated)
    VALUES (?, ?, ?, ?, ?, ?, ?)
  `).run(id, data.projectId, data.category, data.key, data.title, data.content, data.autoGenerated ? 1 : 0)
  return getLoreEntry(db, id)!
}

export function getLoreEntry(db: Database.Database, id: string): LoreEntry | undefined {
  const row = db.prepare('SELECT * FROM lore_entries WHERE id = ?').get(id) as any
  if (!row) return undefined
  return rowToLore(row)
}

export function listLoreEntries(db: Database.Database, projectId: string, category?: LoreCategory): LoreEntry[] {
  const rows = category
    ? db.prepare('SELECT * FROM lore_entries WHERE project_id = ? AND category = ? ORDER BY key').all(projectId, category) as any[]
    : db.prepare('SELECT * FROM lore_entries WHERE project_id = ? ORDER BY category, key').all(projectId) as any[]
  return rows.map(rowToLore)
}

export function upsertLoreEntry(db: Database.Database, data: Omit<LoreEntry, 'id' | 'updatedAt'>): LoreEntry {
  const existing = db.prepare('SELECT id FROM lore_entries WHERE project_id = ? AND category = ? AND key = ?')
    .get(data.projectId, data.category, data.key) as any
  if (existing) {
    db.prepare('UPDATE lore_entries SET title = ?, content = ?, auto_generated = ?, updated_at = datetime(\'now\') WHERE id = ?')
      .run(data.title, data.content, data.autoGenerated ? 1 : 0, existing.id)
    return getLoreEntry(db, existing.id)!
  }
  return createLoreEntry(db, data)
}

export function getContextLayer(db: Database.Database, projectId: string, level: string): ContextLayer | undefined {
  const row = db.prepare('SELECT * FROM context_layers WHERE project_id = ? AND level = ?')
    .get(projectId, level) as any
  if (!row) return undefined
  return { id: row.id, projectId: row.project_id, level: row.level, volumeId: row.volume_id,
    content: row.content, generatedAt: row.generated_at, sourceChapterIds: JSON.parse(row.source_chapter_ids || '[]') }
}

export function upsertContextLayer(db: Database.Database, data: Omit<ContextLayer, 'id' | 'generatedAt'>): ContextLayer {
  const existing = db.prepare('SELECT id FROM context_layers WHERE project_id = ? AND level = ?')
    .get(data.projectId, data.level) as any
  if (existing) {
    db.prepare('UPDATE context_layers SET content = ?, source_chapter_ids = ?, generated_at = datetime(\'now\') WHERE id = ?')
      .run(data.content, JSON.stringify(data.sourceChapterIds), existing.id)
    return getContextLayer(db, data.projectId, data.level)!
  }
  const id = uuid()
  db.prepare('INSERT INTO context_layers (id, project_id, level, volume_id, content, source_chapter_ids) VALUES (?, ?, ?, ?, ?, ?)')
    .run(id, data.projectId, data.level, data.volumeId ?? null, data.content, JSON.stringify(data.sourceChapterIds))
  return getContextLayer(db, data.projectId, data.level)!
}

function rowToLore(row: any): LoreEntry {
  return {
    id: row.id, projectId: row.project_id, category: row.category, key: row.key,
    title: row.title, content: row.content, autoGenerated: !!row.auto_generated,
    updatedAt: row.updated_at,
  }
}
