export type LoreCategory = 'world' | 'characters' | 'style'

export interface LoreEntry {
  id: string
  projectId: string
  category: LoreCategory
  key: string
  title: string
  content: string
  autoGenerated: boolean
  updatedAt: string
}

export interface ContextLayer {
  id: string
  projectId: string
  level: 'L0' | 'L1' | 'L2'
  volumeId?: string
  content: string
  generatedAt: string
  sourceChapterIds: string[]
}
